"""empty message

Revision ID: 09f37a26e0f9
Revises: b5237cc75ab2
Create Date: 2021-02-24 10:05:29.067217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09f37a26e0f9'
down_revision = 'b5237cc75ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('datum_belongs_to_field', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'data', 'fields', ['datum_belongs_to_field'], ['field_uid'])
    op.drop_column('data', 'datum_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('datum_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'datum_belongs_to_field')
    # ### end Alembic commands ###
