"""empty message

Revision ID: 2e4d851f9674
Revises: ebf5a6c6c332
Create Date: 2021-02-25 12:52:42.541488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e4d851f9674'
down_revision = 'ebf5a6c6c332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trials',
    sa.Column('trial_id', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trial_id')
    )
    op.add_column('data', sa.Column('datum_belongs_to_trial', sa.String(length=11), nullable=True))
    op.create_foreign_key(None, 'data', 'trials', ['datum_belongs_to_trial'], ['trial_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'datum_belongs_to_trial')
    op.drop_table('trials')
    # ### end Alembic commands ###
