"""empty message

Revision ID: 344a1d33188e
Revises: ea838de0cdb7
Create Date: 2021-02-25 19:20:07.410957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344a1d33188e'
down_revision = 'ea838de0cdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('inclusion_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'inclusion_note')
    # ### end Alembic commands ###
