"""empty message

Revision ID: 4825fb679267
Revises: 2e4d851f9674
Create Date: 2021-02-25 13:13:15.361489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4825fb679267'
down_revision = '2e4d851f9674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('datum_value', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'datum_value')
    # ### end Alembic commands ###
