"""empty message

Revision ID: 65fecf9b4bf1
Revises: e2fc6b95949c
Create Date: 2021-03-03 15:30:15.043549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65fecf9b4bf1'
down_revision = 'e2fc6b95949c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('views')
    op.drop_table('fieldsviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fieldsviews',
    sa.Column('fieldview_uid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('view_uid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('field_uid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('field_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_uid'], ['fields.field_uid'], name='fieldsviews_field_uid_fkey'),
    sa.ForeignKeyConstraint(['view_uid'], ['views.view_uid'], name='fieldsviews_view_uid_fkey'),
    sa.PrimaryKeyConstraint('fieldview_uid', name='fieldsviews_pkey')
    )
    op.create_table('views',
    sa.Column('view_uid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('view_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('view_belongs_to_user', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['view_belongs_to_user'], ['users.user_uid'], name='views_view_belongs_to_user_fkey'),
    sa.PrimaryKeyConstraint('view_uid', name='views_pkey')
    )
    # ### end Alembic commands ###
