"""empty message

Revision ID: ac4c6d0b1554
Revises: 344a1d33188e
Create Date: 2021-03-03 10:12:23.635281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4c6d0b1554'
down_revision = '344a1d33188e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('field_include', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'field_include')
    # ### end Alembic commands ###
