"""empty message

Revision ID: b5237cc75ab2
Revises: 8cdeca2046df
Create Date: 2021-02-24 10:03:01.876933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5237cc75ab2'
down_revision = '8cdeca2046df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fields_field_depends_on_fkey', 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'fields', ['field_depends_on'], ['field_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key('fields_field_depends_on_fkey', 'fields', 'data', ['field_depends_on'], ['datum_uid'])
    # ### end Alembic commands ###
