"""empty message

Revision ID: ea838de0cdb7
Revises: 4825fb679267
Create Date: 2021-02-25 13:14:20.544260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea838de0cdb7'
down_revision = '4825fb679267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('inclusion', sa.VARCHAR(), nullable=True))
    op.drop_column('trials', 'datum_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('datum_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trials', 'inclusion')
    # ### end Alembic commands ###
