"""empty message

Revision ID: 54ebc18ddeb4
Revises: 
Create Date: 2021-02-17 15:53:56.932561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54ebc18ddeb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('whitelist',
    sa.Column('domain_uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('domain_uid'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('data',
    sa.Column('datum_uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('datum_name', sa.Text(), nullable=True),
    sa.Column('datum_value', sa.Text(), nullable=True),
    sa.Column('datum_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('datum_depends_on', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_uid'], ),
    sa.ForeignKeyConstraint(['datum_depends_on'], ['data.datum_uid'], ),
    sa.PrimaryKeyConstraint('datum_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('whitelist')
    op.drop_table('users')
    # ### end Alembic commands ###
