"""empty message

Revision ID: c57c264039ff
Revises: 54ebc18ddeb4
Create Date: 2021-02-17 15:57:26.729279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57c264039ff'
down_revision = '54ebc18ddeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('datum_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'datum_note')
    # ### end Alembic commands ###
